<a href="https://colab.research.google.com/github/Bsireesha213/Python-assignment-functions-list-comprehensions-and-Numpy/blob/main/python_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 #FUNCTIONS AND LIST COMPREHENSIONS
# write a function wish(name) that returns "Hello. Good Morning"
def wish(name):
  print(f"Hello,Good Morning {name} ! ")
wish("KSR")

Hello,Good Morning KSR ! 


In [ ]:
#write a function cube(n) that returns the cube of a number(n3)
def cube(n):
  return n**3
cube(2)

8

In [ ]:
#write the function check_even(n) that returns true if the number is even, else false
def check_even(n):
  if n%2==0:
    print("True")
  else:
    print("False")
check_even(9)

False


In [ ]:
#greatest of two(a,b) that return the larger of two numbers
def greatest_of_two(a,b):
  if a>b:
    return a
  else:
    return b
greatest_of_two(6,20)

20

In [ ]:
#count_letters that returns the number of characters in a stirng
def count_letters(s):
  return len(s)
count_letters("sireesha")

8

In [ ]:
#power(value,exp=2) that returns the number raised to the power exp.
def power(value,exp=2):
    return value**2
power(3,2)

9

In [ ]:
# swap(a,b) that returns the two values swapped as tuple
def swap(a,b):
  return b,a
swap(20,30)

(30, 20)

In [ ]:
#add_sub(a,b) that returns both sum and difference of two numbers
def add_sub(a,b):
  return a+b,a-b
add_sub(5,10)

(15, -5)

In [ ]:
#circle_stats (radius) that returns the area a nd circumference as a tuple
def circle_stats(radius):
  return 3.14*radius**2,2*3.14*radius
circle_stats(3)

(28.26, 18.84)

In [ ]:
#min_max_sum(nums) that returns the minimum ,maximum and sum of alist
def min_max_sum(nums):
  return min(nums),max(nums),sum(nums)
min_max_sum([1,2,3,4,5,6])

(1, 6, 21)

In [ ]:
#concat(parts) that joins multiple strings together with spaces
def concat(*parts):
  str1="Hello Everyone"
  str2=" Good Morning"
  str=str1+str2
  return str
concat(str)

'Hello Everyone Good Morning'

In [ ]:
#format_name(first,last="") that returns "last,first" if last name is provided,else "first"
def format_name(first,last=""):
  if last:
    return f"{last} , {first}"
  else:
    return 'first'
format_name(first='podalakur' , last='nellore')

'nellore , podalakur'

In [ ]:
# greet_user(first,last) that returns a message like "welcome,first last!"
def greet_user(first,last):
  return f"welcome, {first} {last}"
greet_user(first='ksr' , last='datavizon')

'welcome, ksr datavizon'

In [ ]:
# write a lambda function add two numbers
def adding(x,y):
  return x+y
adding(10,20)

30

In [ ]:
#recursive function factorial(n) that returns a fatorial of a number
def factorial(n):
  if n==0 or n==1:
    return 1
  else:
    return n*factorial(n-1)
factorial(4)


24

In [ ]:
# create [1,2,3,4] list of their squres
abc=[1,2,3,4]
list(map(lambda x:x*x,abc))

[1, 4, 9, 16]

In [ ]:
#create ["a","b","c"] list of their uppercase versions
abc=['a','b','c']
list(map(lambda x:x.upper(),abc))

['A', 'B', 'C']

In [ ]:
#make a list of even numbers from 1 to 20
even_numbers=list(filter(lambda x:x%2==0,range(1,21)))
print(even_numbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [ ]:
#	Given words = ['apple', 'bee', 'cat'], create [(word, len(word)) for word in words].
words=["apple","bee","cat"]
length=list(map(lambda w:(w,len(w)),words))
print(length)

[('apple', 5), ('bee', 3), ('cat', 3)]


In [ ]:
#From nums = [0,1,2,3], create a list of 'even' or 'odd' strings.
nums=[0,1,2,3,4]
result=list(map(lambda x:"even" if x%2==0 else "odd",nums ))
print(result)

['even', 'odd', 'even', 'odd', 'even']


In [ ]:
#From range(1,50), select numbers divisible by both 2 and 3.
nums=list(range(1,50))
result=list(filter(lambda x:x%2==0 and x%3==0,nums))
print(result)

[6, 12, 18, 24, 30, 36, 42, 48]


In [ ]:
#From ['a b','c d e'], produce a flat list of all words.
words=['a b', 'c d e']
result=list(map(lambda x:x.split(),words))
flat_list= [word  for group in result for word in group]
print(flat_list)


['a', 'b', 'c', 'd', 'e']


In [ ]:
#	Given students = [{'name':'A','score':80}, {'name':'B','score':60}], Create a list of names of students with score ≥ 75.
students=[{'name':'A','score':80},{'name':'B','score':60}]
result=list(map(lambda s: s['name'],filter(lambda s: s['score']>=75,students)))
print(result)


['A']


In [ ]:
#Generate all possible sequences of length 4 from 'abcd' with no repeated letters
import itertools
result=list(itertools.permutations('abcd',4))
print(result)

[('a', 'b', 'c', 'd'), ('a', 'b', 'd', 'c'), ('a', 'c', 'b', 'd'), ('a', 'c', 'd', 'b'), ('a', 'd', 'b', 'c'), ('a', 'd', 'c', 'b'), ('b', 'a', 'c', 'd'), ('b', 'a', 'd', 'c'), ('b', 'c', 'a', 'd'), ('b', 'c', 'd', 'a'), ('b', 'd', 'a', 'c'), ('b', 'd', 'c', 'a'), ('c', 'a', 'b', 'd'), ('c', 'a', 'd', 'b'), ('c', 'b', 'a', 'd'), ('c', 'b', 'd', 'a'), ('c', 'd', 'a', 'b'), ('c', 'd', 'b', 'a'), ('d', 'a', 'b', 'c'), ('d', 'a', 'c', 'b'), ('d', 'b', 'a', 'c'), ('d', 'b', 'c', 'a'), ('d', 'c', 'a', 'b'), ('d', 'c', 'b', 'a')]


In [ ]:
#NUMPY ASSIGNMENT

#import the numpy library using alias
import numpy as np
arr=[1,2,3,4,5]
print(arr)

[1, 2, 3, 4, 5]


In [ ]:
#check the version of numpy
np.__version__

'2.0.2'

In [ ]:
# check the configuration of numpy
np.__config__

<module 'numpy.__config__' from '/usr/local/lib/python3.12/dist-packages/numpy/__config__.py'>

In [ ]:
#create a vector filled with zeros of size 10
import numpy as np
arr1=np.zeros(10,dtype=int)
print(arr1)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#create a zero vector of size 10 with the first element as 1
import numpy as np
arr2 = np.zeros(10, dtype=int)
arr2[4] = 1
print(arr2)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#create a vector with values from 0 to 49
import numpy as np
abc=(np.arange(10,50))
print(abc)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#reverse a vector
import numpy as np
a=[1,2,3,4,5]
print(a[::-1])

[5, 4, 3, 2, 1]


In [ ]:
#create 3*3 matrix with values from 0 to 8
import numpy as np
ab=np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])
print(ab)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#find indices of non zero elements in an array
import numpy as np
arr3=[1,0,2,0,0,8,4,0]
print(np.nonzero(arr3))

(array([0, 2, 5, 6]),)


In [ ]:

#create 3*3 identity matrix
import numpy as np
I=np.eye(3,dtype=int)
print(I)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
#generate a 3*3*3 array with random values
import numpy as np
abc=np.random.rand(3,3,3)
print(abc)

[[[0.60795269 0.60596532 0.08205752]
  [0.71288915 0.29567385 0.11527471]
  [0.53505178 0.10343965 0.32723329]]

 [[0.59809395 0.88015728 0.45979861]
  [0.44589691 0.82647048 0.73104581]
  [0.69445952 0.58969941 0.13174573]]

 [[0.32312416 0.17853078 0.35836341]
  [0.98097058 0.73114298 0.30238377]
  [0.23612474 0.95403469 0.70933035]]]


In [ ]:
#find the min and max values in a 10*10 random matrix
import numpy as np
b=np.random.rand(10,10,)
print(b)
print("minimum_value:",np.min(b))
print("maximum_value:",np.max(b))

[[0.61248158 0.48625441 0.21614073 0.68893112 0.46713563 0.89802994
  0.61429049 0.16409441 0.73980538 0.6866521 ]
 [0.8466903  0.35391056 0.80265664 0.34971818 0.16335702 0.36646465
  0.34162541 0.99448851 0.39186813 0.35855038]
 [0.79065144 0.51109314 0.4934179  0.95433648 0.23564488 0.78919697
  0.16744748 0.36669311 0.37132163 0.60911643]
 [0.36174032 0.45488747 0.52557435 0.85833862 0.15929953 0.20950039
  0.44864439 0.22518886 0.32124766 0.76845822]
 [0.18540559 0.4890802  0.06676047 0.18632022 0.04022894 0.85297167
  0.75151674 0.15002812 0.46615162 0.35126921]
 [0.36447095 0.17293459 0.82431513 0.16190017 0.12937809 0.08815344
  0.48142798 0.8450282  0.32770218 0.5520643 ]
 [0.2037353  0.12236241 0.9518285  0.15192936 0.42149559 0.67524708
  0.9081149  0.50966443 0.29261476 0.04207273]
 [0.1556083  0.70891343 0.36482937 0.12906818 0.3055912  0.70903453
  0.17528363 0.72899271 0.30164695 0.90334148]
 [0.54272018 0.80981859 0.92804967 0.48088652 0.71111611 0.90815158
  0.2859088 

In [ ]:
#calculate a mean value of random vector of size 30
import numpy as np
a=np.random.rand(30)
print(a)
print("mean_value:",np.mean(a))

[0.60770083 0.33389631 0.39629866 0.28579682 0.12727087 0.97433217
 0.35061809 0.67859908 0.15230802 0.01882937 0.96648934 0.2296493
 0.69661664 0.45557293 0.55893666 0.1650451  0.87570846 0.27301476
 0.40258085 0.63659975 0.38968161 0.58124104 0.65912969 0.12587142
 0.99019138 0.27348827 0.07983625 0.28417651 0.81863161 0.45193583]
mean_value: 0.46133492101827345


In [ ]:
#perform a matrix multiplication between two matrices
import numpy as np
a=np.array([[1,2],
            [3,4]])
b=np.array([[3,4],
            [4,5]])
print(np.dot(a,b))


[[11 14]
 [25 32]]


In [ ]:
#create a 2d array with 1s on border and 0s inside
import numpy as np
arr5=np.ones((5,5),dtype=int)
arr5[1:-1,1:-1]=0
print(arr5)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#what is the results of operations like 0*np.nan,np.nan==np.nan etc
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)

nan
False


In [ ]:
#create a matrix with values below the diagonal
import numpy as np
a=np.arange(1,10)
b=a.reshape(3,3)
diagonal=np.tril(b)
print(diagonal)

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
#create a checkerboard pattern in an 8*8 matrix
import numpy as np
a=np.zeros((8,8),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#find the index of a flat element in 3d shape
import numpy as np
arr=np.arange(1,28)
print(arr.reshape(3,3,3))
flat=arr.flatten()
print(flat)
index=np.where(flat==20)[0][0]
print(index)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
19


In [ ]:
#create a checkerboard pattern using numpy tile function
import numpy as np
a=np.array([[0,1],
            [1,0]])
tiled=np.tile(a,(4,4))
print(tiled)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#sort a random array
import numpy as np
arr=np.random.rand(1,10)
print(arr)
print("sorted_array:",np.sort(arr))

[[0.27309619 0.24460201 0.76228129 0.65105515 0.66466513 0.97679451
  0.71369616 0.32198836 0.13252977 0.80423939]]
sorted_array: [[0.13252977 0.24460201 0.27309619 0.32198836 0.65105515 0.66466513
  0.71369616 0.76228129 0.80423939 0.97679451]]


In [ ]:
#create a 5*5 matrix with row values ranging from 0 to 4
import numpy as np
arr = np.arange(0, 5)
tiled = np.tile(arr,(5,1))
print(tiled)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#normalise a matrix(values between 0 and 1)
import numpy as np
a=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
norm=(a-a.min())/(a.max()-a.min())
print(norm)

[[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [ ]:
#negate values between two given numbers in a vector
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr>=2)&(arr<=6)]*=-1
print(arr)

[ 1 -2 -3 -4 -5 -6  7  8  9 10]


In [ ]:
#what is the output of sum(range(5),-1)vs np.sum(range(5),-1)
import numpy as np
a=np.arange(0,5)
print(a)
print(sum(a,-1))
print(np.sum(a,-1))

[0 1 2 3 4]
9
10


In [ ]:
#check if two arrays are equal
import numpy as np
a=np.array([1,2,3,4])
b=np.array([1,2,3,5])
c=np.array([1,2,3,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))
print(np.array_equal(b,c))

False
True
False


In [ ]:
#sum an array faster than using np.sum
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(arr.sum())


15
15


In [ ]:
#divide integers or floats by zero in numpy
import numpy as np
a=np.array([1,2,3,4],dtype=int)
b=np.array([0,0,0,0],dtype=int)
print(a/b)
c=np.array([1.0,2.0,3.0],dtype=float)
d=np.array([0.0,0.0,0.0],dtype=float)
print(c/d)

[inf inf inf inf]
[inf inf inf]


/tmp/ipython-input-1194319995.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a/b)
/tmp/ipython-input-1194319995.py:7: RuntimeWarning: divide by zero encountered in divide
  print(c/d)


In [ ]:
#round a float array away from zero
import numpy as np
arr=np.array([1.0,-3.4,2.3,-9.4,-1.2])
res=np.sign(arr)*np.ceil(np.abs(arr))
print(res)

[  1.  -4.   3. -10.  -2.]


In [ ]:
#use a generator to create numpy array
import numpy as np
a=(i for i in range(10))
arr=np.fromiter(a,dtype=int)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#create array with evenly spaced values between 0 t0 1 (excluded)
import numpy as np
arr=np.arange(0.1,1.0,0.2)
print(arr)

[0.1 0.3 0.5 0.7 0.9]


In [ ]:
#make a numpy array read only
import numpy as np
arr=np.arange(10)
print(arr)
arr.flags.writeable=False
arr[2]=7

[0 1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

In [ ]:
#how do you extract the integer part of a float using multiple methods
import numpy as np
arr=np.array([2.3,4.0,-2.9,3.5])
print(np.ceil(arr))
print(np.floor(arr))
print(np.trunc(arr))

[ 3.  4. -2.  4.]
[ 2.  4. -3.  3.]
[ 2.  4. -2.  3.]


In [ ]:
#create cauchy matrix with two arrays
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
c=1.0/(x[:,None]-y[None,:])
print(c)



[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [ ]:
#how do you replace a maximum value in an array with zero
import numpy as np
arr=np.array([1,2,3,4,9,18,39])
arr[arr==arr.max()]=0
print(arr)


[ 1  2  3  4  9 18  0]


In [ ]:
#how do you display all values in a large array
import numpy as np
arr=np.arange(0,100)
np.set_printoptions(threshold=np.inf)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#closest value to a given scalar in an array
import numpy as np
arr=np.array([1,20,34,98,16])
num=28
c=arr[np.abs(arr-num).argmin()]
print(c)


34


In [ ]:
#sort a 2D array based on the values of one column
import numpy as np
arr=np.array([
    [4,5,6],
    [1,2,3],
    [7,8,9]
    ])
s= arr [arr [:, 1] . argsort()]
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#check  if a 2d array contains any null columns
import numpy as np
arr=np.array([[1,0,4],
              [3,0,8],
              [8,0,3]])
c=np.all(arr==0,axis=0)
print(c)
print(np.any(c))

[False  True False]
True


In [ ]:
#nearest value of given number in a numpy array
import numpy as np
arr=np.array([1,43,26,73,29,8,17])
num=12
n=arr[np.abs(arr-num).argmin()]
print(n)

8


In [ ]:
#accumulate values into an array based on the indices
import numpy as np
arr=np.zeros(5)
idx=[0,1,2,1,3]
val=[1,2,3,4,5]
np.add.at(arr,idx,val)
print(arr)


[0. 0. 0. 0. 0.]
[1. 6. 3. 5. 0.]


In [ ]:
#how do you efficiently get the diagonal of a matrix dot product
import numpy as np
a=np.random.rand(3,3)
b=np.random.rand(3,3)
c=a@b
print(c)
diagonal=np.diag(c)
print("diagonal_matrix is:",diagonal)

[[0.54983599 0.56735874 0.84616214]
 [0.43022142 1.0030105  0.97851824]
 [0.96207846 1.21552899 1.11181219]]
diagonal_matrix is: [0.54983599 1.0030105  1.11181219]


In [ ]:
#interleave a vector with a fixed number of zeros
import numpy as np
arr=np.array([1,2,3])
n=2
out=np.zeros(len(arr)*(n+1),int)
out[::n+1]=arr
print(out)

[1 0 0 2 0 0 3 0 0]


In [ ]:
#how do you multiply a (5,5,3) array with a (5,5) array elment-wise
import numpy as np
a=np.random.rand(5,5,3)
b=np.random.rand(5,5)
result=a*b[:, :, np.newaxis]
print(result)



[[[0.03941078 0.00349438 0.02273982]
  [0.4447147  0.69197554 0.17444437]
  [0.19816993 0.04922927 0.18413169]
  [0.24944061 0.34458793 0.03698297]
  [0.37228739 0.38095077 0.0752789 ]]

 [[0.71645884 0.67996884 0.53780915]
  [0.01151744 0.08119458 0.09068264]
  [0.0047642  0.01306936 0.01528862]
  [0.38302936 0.80719198 0.48503133]
  [0.58599477 0.52390927 0.28137541]]

 [[0.0206614  0.33102539 0.03417222]
  [0.015194   0.24059889 0.24181812]
  [0.29010853 0.14239589 0.15346718]
  [0.14895193 0.12168215 0.08723882]
  [0.17629183 0.78594962 0.23040648]]

 [[0.26195702 0.43824531 0.27428655]
  [0.00905044 0.00493644 0.01616233]
  [0.03351792 0.14153045 0.07150996]
  [0.50123385 0.05745841 0.29804252]
  [0.05722187 0.41143097 0.23136936]]

 [[0.00877816 0.02058383 0.01660521]
  [0.34408792 0.08320387 0.26470637]
  [0.37766775 0.01671651 0.48591075]
  [0.57892975 0.19948425 0.46755874]
  [0.14995188 0.21930679 0.49387623]]]


In [ ]:
# how do you swap two rows in a matrix
import numpy as np
arr = np.arange(9).reshape(3, 3)
print("Original matrix:",arr)
arr[[0, 2]] = arr[[2, 0]]
print("\n after swapping:",arr)


Original matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]

 after swapping: [[6 7 8]
 [3 4 5]
 [0 1 2]]


In [ ]:
#vertically and horizontally stack two arrays
import numpy as np
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#apply a custom function to each element of an array
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
b=arr**2+5
print(b)

[ 6  9 14 21 30 41 54]


In [ ]:
#how do you remove duplicate rows in a 2d array
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [1,2,3],
              [7,8,9]])
b=np.unique(arr,axis=0)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#filter  rows based on a specific column value
import numpy as np
arr=np.array([[10,15,20],
              [30,40,35],
              [40,50,60]])
b=arr[arr[:, 1]>=30]
print(b)

[[30 40 35]
 [40 50 60]]


In [ ]:
#print column_wise and row_wise minimum/maximum indices
import numpy as np
arr=np.array([[23,34,45],
              [17,56,30],
              [24,23,68]])
print("column_wise min:",np.argmin(arr,axis=0))
print("column_wise max:",np.argmax(arr,axis=0))
print("row_wise min:",np.argmin(arr,axis=1))
print("row_wise max:",np.argmax(arr,axis=1))

column_wise min: [1 2 1]
column_wise max: [2 1 2]
row_wise min: [0 0 1]
row_wise max: [2 1 2]


In [ ]:
#how do you flatten and sort 2D array
import numpy as np
arr=np.array([[1,2,32],
              [23,54,2],
              [45,62,32]])
a=arr.flatten()
print(a)
print(np.sort(a))

[ 1  2 32 23 54  2 45 62 32]
[ 1  2  2 23 32 32 45 54 62]


In [ ]:
#how do you find shape and number of elements in an array
import numpy as np
arr=np.array([[10,34,26],
              [45,28,34]])
print(arr.shape)
print(arr.size)

(2, 3)
6


In [ ]:
# how do you reshape an array without changing its data
import numpy as np
arr=np.arange(9)
print(arr)
print(arr.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#how do you flatten a multi-dimensional array
import numpy as np
arr=np.arange(1,10).reshape(3,3)
a=arr.flatten()
print(a)


[1 2 3 4 5 6 7 8 9]


In [ ]:
# how do you compute element-wise maximum/minimum of two arrays
import numpy as np
arr=np.arange(1,5)
arr1=np.arange(6,10)
print(arr,arr1)
print("maximum_array:",np.maximum(arr,arr1))
print("minimum_array:",np.minimum(arr,arr1))


[1 2 3 4] [6 7 8 9]
maximum_array: [6 7 8 9]
minimum_array: [1 2 3 4]


In [ ]:
# how do you broadcast arrays with diiferent shapes
import numpy as np
arr=np.array([[1,2,3,4],
              [4,5,6,7]])
arr1=np.array([10,20,30,40])
print(arr+arr1)
arr2=np.array([[10],
               [20]])

print(arr2+arr)

[[11 22 33 44]
 [14 25 36 47]]
[[11 12 13 14]
 [24 25 26 27]]


In [ ]:
# how do you tanspose a matrix and perform dot products
import numpy as np
arr=np.arange(1,7).reshape(2,3)
print(arr)
a=(arr.T)
print(a)
result=np.dot(arr,a)
print(result)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [ ]:
#how do you check Nan or infinite values in an array
import numpy as np
arr=np.array([1,34,np.nan,45,np.inf])
print(arr)
print(np.isnan(arr))
print(np.isinf(arr))

[ 1. 34. nan 45. inf]
[False False  True False False]
[False False False False  True]


In [ ]:
# how do you extract diagonal,upper and lower triangles from a matrix
import numpy as np
arr=np.arange(1,10).reshape(3,3)
print(arr)
diagonal=np.diag(arr)
upper=np.triu(arr)
lower=np.tril(arr)
print("diagonal_triangle:",diagonal)
print("upper_triangle:",upper)
print("lower_triangle:",lower)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal_triangle: [1 5 9]
upper_triangle: [[1 2 3]
 [0 5 6]
 [0 0 9]]
lower_triangle: [[1 0 0]
 [4 5 0]
 [7 8 9]]
